# Generated by Django 5.2.7 on 2025-11-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.CharField(max_length=200, unique=True)),
                ('version', models.CharField(max_length=100)),
                ('release_date', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('major', 'major'), ('minor', 'minor')], max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('source', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
