# Generated by Django 5.2.7 on 2025-12-02 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_project_stackcomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureUpdateCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.CharField(db_index=True, max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('expected_date', models.DateField(blank=True, help_text='Expected release date if known', null=True)),
                ('confidence', models.IntegerField(default=50, help_text='Confidence score 0-100% based on source reliability', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('features', models.TextField(blank=True, help_text='Summary of planned features/changes')),
                ('source', models.URLField(blank=True, help_text='URL to announcement/roadmap')),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('confirmed', 'Confirmed'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='detected', max_length=20)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('promoted_to_release', models.ForeignKey(blank=True, help_text='Links to UpdateCache entry when this future update is released', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='future_predictions', to='tracker.updatecache')),
            ],
            options={
                'verbose_name': 'Future Update',
                'verbose_name_plural': 'Future Updates',
                'ordering': ['-confidence', '-updated_at'],
                'unique_together': {('library', 'version')},
            },
        ),
    ]
