# Generated by Django 5.2.7 on 2025-12-04 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_futureupdatecache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatecache',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Update Cache', 'verbose_name_plural': 'Update Caches'},
        ),
        migrations.AddField(
            model_name='updatecache',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updatecache',
            name='project',
            field=models.ForeignKey(default=1, help_text='Project this update cache belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='update_caches', to='tracker.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='updatecache',
            name='library',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='updatecache',
            unique_together={('project', 'library')},
        ),
    ]
