# Generated by Django 5.2.7 on 2025-12-08 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_add_project_to_updatecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureupdatecache',
            name='last_change_reason',
            field=models.TextField(blank=True, help_text="Reason for last confidence/info change (e.g., 'Featured on official site')"),
        ),
        migrations.AddField(
            model_name='futureupdatecache',
            name='previous_confidence',
            field=models.IntegerField(blank=True, help_text='Previous confidence level before last update', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
