# Generated by Django 5.2.7 on 2025-12-23 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_futureupdatecache_last_change_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('key', models.CharField(db_index=True, help_text="Normalized key for searching (e.g. 'react', 'python')", max_length=200)),
                ('component_type', models.CharField(choices=[('library', 'Library'), ('language', 'Language'), ('tool', 'Tool')], default='library', max_length=50)),
                ('latest_version', models.CharField(blank=True, max_length=100)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('homepage_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stackcomponent',
            name='library_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_components', to='tracker.library'),
        ),
        migrations.CreateModel(
            name='LibraryRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_security_release', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='tracker.library')),
            ],
            options={
                'ordering': ['-release_date', '-created_at'],
                'unique_together': {('library', 'version')},
            },
        ),
    ]
