# Generated by Django 5.2.7 on 2025-12-31 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_library_stackcomponent_library_ref_libraryrelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='api_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='library',
            name='detection_trust_level',
            field=models.IntegerField(blank=True, help_text='Trust level of the latest version detection source (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='library',
            name='last_api_call_successful',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='library',
            name='registry_type',
            field=models.CharField(blank=True, help_text="Registry type hint (e.g. 'pypi', 'npm')", max_length=50),
        ),
        migrations.AddField(
            model_name='libraryrelease',
            name='detection_source',
            field=models.CharField(blank=True, help_text="Source of detection (e.g. 'api:trust_100', 'serper_groq')", max_length=100),
        ),
    ]
