# Generated by Django 5.2.7 on 2025-12-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_library_api_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureupdatecache',
            name='confirmation_count',
            field=models.IntegerField(default=1, help_text='Number of independent sources confirming this version'),
        ),
        migrations.AddField(
            model_name='futureupdatecache',
            name='detection_method',
            field=models.CharField(blank=True, choices=[('registry_prerelease', 'Registry Pre-Release'), ('github_release', 'GitHub Pre-Release'), ('github_milestone', 'GitHub Milestone'), ('github_roadmap', 'GitHub Roadmap File'), ('official_website', 'Official Website/RSS'), ('serper_groq', 'Web Search (Fallback)')], help_text='Method used to detect this future version', max_length=50),
        ),
        migrations.AddField(
            model_name='futureupdatecache',
            name='is_published_prerelease',
            field=models.BooleanField(default=False, help_text='True if this version is actually installable (e.g. on npm/pypi)'),
        ),
        migrations.AddField(
            model_name='futureupdatecache',
            name='milestone_completion_percent',
            field=models.IntegerField(blank=True, help_text='GitHub milestone completion % if applicable', null=True),
        ),
        migrations.AddField(
            model_name='futureupdatecache',
            name='prerelease_type',
            field=models.CharField(blank=True, choices=[('alpha', 'Alpha'), ('beta', 'Beta'), ('rc', 'Release Candidate'), ('dev', 'Development'), ('milestone', 'Milestone Only'), ('roadmap', 'Roadmap Only')], help_text='Type of pre-release (alpha, beta, rc, etc.)', max_length=20),
        ),
    ]
