# Generated by Django 5.2.7 on 2026-01-04 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_futureupdatecache_confirmation_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.CharField(blank=True, db_index=True, max_length=200)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('status_text', models.TextField(blank=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True)),
                ('error_text', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, help_text='Project targeted by this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_records', to='tracker.project')),
                ('update_cache', models.ForeignKey(blank=True, help_text='Associated UpdateCache entry when applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_records', to='tracker.updatecache')),
            ],
            options={
                'verbose_name': 'Notification Record',
                'verbose_name_plural': 'Notification Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
