# Generated by Django 5.2.7 on 2026-01-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_notificationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecache',
            name='detection_method',
            field=models.CharField(blank=True, choices=[('registry_api', 'Registry API'), ('serper_groq', 'Web Search (Serper+Groq)'), ('github_release', 'GitHub Release'), ('official_website', 'Official Website'), ('unknown', 'Unknown')], default='unknown', help_text='Method used to detect this version', max_length=50),
        ),
    ]
