# Generated by Django 5.2.7 on 2026-01-04 03:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_updatecache_detection_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='min_confidence_threshold',
            field=models.IntegerField(default=50, help_text='Only notify about future updates with confidence >= this threshold (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='project',
            name='notify_paused',
            field=models.BooleanField(default=False, help_text='Temporarily pause notifications for this project'),
        ),
        migrations.CreateModel(
            name='FutureUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.CharField(db_index=True, max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('old_confidence', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('new_confidence', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('change_reason', models.CharField(blank=True, choices=[('initial_detection', 'Initial Detection'), ('source_confirmed', 'Source Confirmed'), ('milestone_updated', 'Milestone Updated'), ('manual_adjustment', 'Manual Adjustment'), ('source_removed', 'Source Removed'), ('other', 'Other')], default='other', max_length=100)),
                ('change_notes', models.TextField(blank=True, help_text='Additional context about this change')),
                ('detection_method', models.CharField(blank=True, max_length=50)),
                ('future_update', models.ForeignKey(help_text='Associated FutureUpdateCache entry', on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='tracker.futureupdatecache')),
            ],
            options={
                'verbose_name': 'Future Update History',
                'verbose_name_plural': 'Future Update Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
