# Generated by Django 5.2.7 on 2026-07-03 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_projects_to_first_user(apps, schema_editor):
    project_model = apps.get_model('tracker', 'Project')
    user_app, user_model = settings.AUTH_USER_MODEL.split('.')
    user_model = apps.get_model(user_app, user_model)
    owner = user_model.objects.filter(is_superuser=True).order_by('id').first()
    if owner is None:
        owner = user_model.objects.order_by('id').first()
    if owner is None:
        return
    project_model.objects.filter(owner__isnull=True).update(owner_id=owner.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_project_min_confidence_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns and can manage this project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(assign_existing_projects_to_first_user, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ProjectFutureNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('status_text', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('future_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_notifications', to='tracker.futureupdatecache')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_notifications', to='tracker.project')),
            ],
            options={
                'verbose_name': 'Project Future Notification',
                'verbose_name_plural': 'Project Future Notifications',
                'ordering': ['-updated_at'],
                'unique_together': {('project', 'future_update')},
            },
        ),
    ]
