# Generated by Django 5.2.7 on 2026-07-04 16:35

import django.db.models.deletion
from django.db import migrations, models


def backfill_update_events(apps, schema_editor):
    update_cache_model = apps.get_model('tracker', 'UpdateCache')
    update_event_model = apps.get_model('tracker', 'UpdateEvent')
    events = []
    for cache in update_cache_model.objects.all().iterator():
        events.append(
            update_event_model(
                project_id=cache.project_id,
                update_cache_id=cache.id,
                library=cache.library,
                version=cache.version,
                release_date=cache.release_date,
                category=cache.category,
                summary=cache.summary,
                source=cache.source,
                detection_method=cache.detection_method,
                notification_success=None,
            )
        )
    if events:
        update_event_model.objects.bulk_create(events, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_project_owner_projectfuturenotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.CharField(db_index=True, max_length=200)),
                ('from_version', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('release_date', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('major', 'major'), ('minor', 'minor'), ('future', 'future')], max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('source', models.URLField(blank=True)),
                ('detection_method', models.CharField(blank=True, choices=[('registry_api', 'Registry API'), ('serper_groq', 'Web Search (Serper+Groq)'), ('github_release', 'GitHub Release'), ('official_website', 'Official Website'), ('unknown', 'Unknown')], default='unknown', help_text='Method used to detect this version', max_length=50)),
                ('notification_success', models.BooleanField(blank=True, null=True)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_events', to='tracker.project')),
                ('update_cache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tracker.updatecache')),
            ],
            options={
                'verbose_name': 'Update Event',
                'verbose_name_plural': 'Update Events',
                'ordering': ['-updated_at'],
                'unique_together': {('project', 'library', 'version', 'category')},
            },
        ),
        migrations.RunPython(backfill_update_events, migrations.RunPython.noop),
    ]
