# Generated by Django 5.2.7 on 2026-09-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_dailycheckrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='last_future_check_at',
            field=models.DateTimeField(blank=True, help_text='When future/pre-release versions were last checked. Tracked separately from last_checked_at because pre-releases appear less often than stable ones and are checked less frequently.', null=True),
        ),
    ]
